const router = require('express').Router();
const validate = require('../middlewares/validate');
const { RegisterSchema, LoginSchema } = require('../validators/auth.validators');
const ctrl = require('../controllers/auth.controller');
const { requireAuth } = require('../middlewares/auth.middleware');
router.post('/register', validate(RegisterSchema), ctrl.register);
router.post('/login', validate(LoginSchema), ctrl.login);
router.post('/refresh', ctrl.refresh);
router.post('/logout', ctrl.logout);
router.get('/me', requireAuth, ctrl.me);
module.exports = router;
